const SLIDE_ROUTES = [
["slides/2023/LT/函館市電LT/opening/", {"source":"index.html","date":"2023/9/18","title":"函館市電LT オープニング","description":"函館市電LTの開会用の資料です。"}],
["slides/2023/LT/函館市電LT/content/", {"source":"index.html","date":"2023/9/18","title":"行かなきゃ人生終了！道南の素晴らしいロードサイド3選","description":"函館市電LTの発表資料です。"}],
["slides/2023/LT/TOGATTA/vol4/", {"source":"index.html","date":"2023/9/30","title":"読むWM tinyWM をちゃんと読む","description":"tinyWMの処理の流れを理解し、X11でのウインドウマネージャ開発の感覚を掴む"}],
["slides/2023/LT/ゆるちとせ202310/", {"source":"index.html","date":"2023/10/15","title":"函館市電LTのあらまし","description":"函館市電LT開催までの流れです。"}],
["slides/2023/LT/未来祭LT/", {"source":"index.html","date":"2023/10/07","title":"読むWM tinyWM をちゃんと読む","description":"tinyWMの処理の流れを理解し、X11でのウインドウマネージャ開発の感覚を掴む"}],
["slides/2023/LT/DHSynapseLT会/1202/", {"source":"index.html","date":"2023/12/2","title":"函館市電LTのあらまし","description":"函館市電LT開催までの流れ(改訂版)です。"}],
["slides/2023/LT/ゆるい勉強会in旭川/yuruasa/", {"source":"index.html","date":"2023/9/10","title":"MIERUNEインターンに行ってきた","description":"ゆるい勉強会(旭川)での発表内容です。"}],
["slides/2023/FUNAI/9_25/", {"source":"index.html","date":"2023/9/30","title":"FUNAI輪読会資料: 第5章 誤差逆伝播法 2/2","description":"ゼロから作るDeepLearning 5章 誤差逆伝播法 5.4-5.8の資料です。"}],
["slides/2023/FUNAI/9_12/", {"source":"index.html","date":"2023/9/12","title":"FUNAI輪読会資料: 第5章 誤差逆伝播法 1/2","description":"ゼロから作るDeepLearning 5章 誤差逆伝播法 5.1-5.3の資料です。"}],
["slides/2023/新雪プログラム/1201/", {"source":"index.html","date":"2023/12/1","title":"12月進捗報告","description":"新雪プログラムで行っているプロジェクトの進捗報告です。"}],
["slides/2023/新雪プログラム/8合目会議/", {"source":"index.html","date":"2023/11/4","title":"新雪プログラム 中間報告会","description":"新雪プログラムで行っているプロジェクトの進捗報告です。"}],
["slides/2023/新雪プログラム/ブースト会議/", {"source":"index.html","date":"2023/9/17","title":"新雪プログラム ブースト会議","description":"新雪プログラムのプロジェクト「ゲーム・映像表現の可能性を広げる地形生成ライブラリの開発」の説明資料です。"}],
["slides/2023/Others/mierune/", {"source":"index.html","date":"2023/9/8","title":"MIERUNEインターンシップ 成果発表","description":"MIERUNE Inc. インターンシップでの成果発表の資料です。"}],
];
