const SLIDE_ROUTES = [
["slides/2024/新雪プログラム/0113/", {"source":"index.html","date":"2024/01/13","title":"新雪プログラム DEMO DAY","description":"新雪プログラムで行っているプロジェクトの最終報告です。"}],
["slides/2024/Mariconf運営/サークル紹介/", {"source":"index.html","date":"2024/4/5","title":"Mariners' Conference サークル紹介","description":"2024年度 Mariners' Conferenceのサークル紹介です。"}],
["slides/2024/LT/ゆるすぎ0130/", {"source":"index.html","date":"2024/01/30","title":"オープンソースライセンス学び直し","description":"よく使ういろいろなライセンスの学び直し"}],
["slides/2024/LT/自己紹介LT/content/", {"source":"index.html","date":"2024/4/14","title":"自己紹介LT","description":"自己紹介LT"}],
["slides/2024/LT/自己紹介LT/closing/", {"source":"index.html","date":"2024/4/14","title":"自己紹介LTクロージング","description":"クロージングスライドです。"}],
["slides/2024/LT/会津合同/content/", {"source":"index.html","date":"2024/02/15","title":"我が家のゴミ・Ops","description":"ゴミが溜まって大変なことになる問題を解決するシステム"}],
["slides/2024/LT/会津合同/welcome/", {"source":"index.html","date":"2024/02/15","title":"はこだて未来大へようこそ","description":"はこだて未来大を紹介します"}],
["slides/2024/ラボユース/成果発表会/", {"source":"index.html","date":"2024/3/26","title":"Linuxウインドウマネージャ開発を通じた良い設計へのアプローチ","description":"サイボウズ・ラボユースの成果発表の資料"}],
["slides/2023/新雪プログラム/1201/", {"source":"index.html","date":"2023/12/1","title":"12月進捗報告","description":"新雪プログラムで行っているプロジェクトの進捗報告です。"}],
["slides/2023/新雪プログラム/8合目会議/", {"source":"index.html","date":"2023/11/4","title":"新雪プログラム 中間報告会","description":"新雪プログラムで行っているプロジェクトの進捗報告です。"}],
["slides/2023/新雪プログラム/ブースト会議/", {"source":"index.html","date":"2023/9/17","title":"新雪プログラム ブースト会議","description":"新雪プログラムのプロジェクト「ゲーム・映像表現の可能性を広げる地形生成ライブラリの開発」の説明資料です。"}],
["slides/2023/LT/DHSynapseLT会/1202/", {"source":"index.html","date":"2023/12/2","title":"函館市電LTのあらまし","description":"函館市電LT開催までの流れ(改訂版)です。"}],
["slides/2023/LT/ゆるちとせ202310/", {"source":"index.html","date":"2023/10/15","title":"函館市電LTのあらまし","description":"函館市電LT開催までの流れです。"}],
["slides/2023/LT/未来祭LT/", {"source":"index.html","date":"2023/10/07","title":"読むWM tinyWM をちゃんと読む","description":"tinyWMの処理の流れを理解し、X11でのウインドウマネージャ開発の感覚を掴む"}],
["slides/2023/LT/ゆるい勉強会in旭川/yuruasa/", {"source":"index.html","date":"2023/9/10","title":"MIERUNEインターンに行ってきた","description":"ゆるい勉強会(旭川)での発表内容です。"}],
["slides/2023/LT/函館市電LT/content/", {"source":"index.html","date":"2023/9/18","title":"行かなきゃ人生終了！道南の素晴らしいロードサイド3選","description":"函館市電LTの発表資料です。"}],
["slides/2023/LT/函館市電LT/opening/", {"source":"index.html","date":"2023/9/18","title":"函館市電LT オープニング","description":"函館市電LTの開会用の資料です。"}],
["slides/2023/LT/TOGATTA/vol4/", {"source":"index.html","date":"2023/9/30","title":"読むWM tinyWM をちゃんと読む","description":"tinyWMの処理の流れを理解し、X11でのウインドウマネージャ開発の感覚を掴む"}],
["slides/2023/Others/mierune/", {"source":"index.html","date":"2023/9/8","title":"MIERUNEインターンシップ 成果発表","description":"MIERUNE Inc. インターンシップでの成果発表の資料です。"}],
["slides/2023/FUNAI/9_25/", {"source":"index.html","date":"2023/9/30","title":"FUNAI輪読会資料: 第5章 誤差逆伝播法 2/2","description":"ゼロから作るDeepLearning 5章 誤差逆伝播法 5.4-5.8の資料です。"}],
["slides/2023/FUNAI/9_12/", {"source":"index.html","date":"2023/9/12","title":"FUNAI輪読会資料: 第5章 誤差逆伝播法 1/2","description":"ゼロから作るDeepLearning 5章 誤差逆伝播法 5.1-5.3の資料です。"}],
];
