name: Auto Build and Commit

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: make build-all

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -a -m "[build] $(date +'%Y/%m/%d')"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
